---
- name: "Run ucp container to install DUCP as controller"
  sudo: yes
  docker:
    name: ucp
    image: docker/ucp
    state: started
    pull: always
    detach: False
    stdin_open: True
    tty: True
    command: install --san "{{ extip }}"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env:
      UCP_ADMIN_USER: "{{ ucp_admin_user }}"
      UCP_ADMIN_PASSWORD: "{{ ucp_admin_password }}"
- name: "Wait for ucp installation container to finish"
  sudo: yes
  shell: docker wait ucp
- name: "Register certificate fingerprint"
  sudo: yes
  shell: "docker run -ti -v /var/run/docker.sock:/var/run/docker.sock docker/ucp fingerprint | awk -F= '{ print $2 }'"
  register: ducp_controller_fingerprint
