---
- name: "Run ucp container to join DUCP cluster as replica"
  sudo: yes
  docker:
    name: ucp
    image: dockerorca/ucp
    state: started
    pull: always
    detach: False
    stdin_open: True
    tty: True
    command: join --replica --san "{{ extip }}" --url https://"{{ hostvars['ducp-controller']['extip'] }}" --fingerprint "{{ hostvars['ducp-controller']['ducp_controller_fingerprint'].stdout }}"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env:
      REGISTRY_EMAIL: "{{ hub_registry_email }}"
      REGISTRY_USERNAME: "{{ hub_registry_username }}"
      REGISTRY_PASSWORD: "{{ hub_registry_password }}"
      UCP_ADMIN_USER: "{{ ucp_admin_user }}"
      UCP_ADMIN_PASSWORD: "{{ ucp_admin_password }}"
- name: "Wait for ucp installation container to finish"
  sudo: yes
  shell: docker wait ucp
